services:
  cinelegas:
    image: cinelegas/vlc:latest
    restart: "unless-stopped"
    shm_size: "2gb"
    ports:
      - "100.66.162.51:8090:8080"
      - "100.66.162.51:53000-53100:53000-53100/udp"
    environment:
      NEKO_DESKTOP_SCREEN: 1280x720@30
      NEKO_MEMBER_MULTIUSER_USER_PASSWORD: neko
      NEKO_MEMBER_MULTIUSER_ADMIN_PASSWORD: admin
      NEKO_WEBRTC_EPR: 53000-53100
      NEKO_WEBRTC_ICELITE: 0
